### ISSUE TITLE
Documentation cleanup needed?

### ISSUE THREAD

**Issue by Daniel314** [knipknap/Gelatin#10]
The main Gelatin example at https://github.com/knipknap/Gelatin/wiki has a couple of references to: out.leave()

However, the Gelatin Syntax Reference makes no reference to this function (nor does Gelatin/compiler/Context.py).  I'm assuming that it no longer does anything.  Perhaps references to it should be removed from the main Gelatin example?

**Comment by knipknap** [comment]
Thanks, I have removed the out.leave() statement.
