### ISSUE TITLE
Special Characters fails in string

### ISSUE THREAD

**Issue by Gergar** [knipknap/Gelatin#14]
Hi I am having a very strange situation when a "description" has an & on it, it makes it fail for some reason... here an example

line to be "tokenized" and translated
ip access-list standard my_long_description_with_an_&_as_it_fails

The output in JSON is:
                    **"@description": "\\"my_long_description_with_an_",** 
                    "permit": {
                        "@mask": "0.0.0.x", 
                        "@family": "x.x.x.x"
                    }
The output if I remove the "&" or any other string...
                    **"@description": "my_long_description_with_an_as_it_fails",** 
                    "permit": {
                        "@mask": "0.0.0.x", 
                        "@family": "x.x.x.x"
                    }

Grammar (I reduced to exemplify... the issue is at the check_list_items function... and only in that use case:
define word /\w+/
define name /[a-zA-Z0-9]+[\-\_a-zA-Z0-9]*/
define description /[^\r\n]+/

grammar access_list_items(default):
    match /(?:permit|deny)/ fs name fs word fs word nl:
        out.add('$0/$2?inbound="$4"&outbound="$6"')
    do.return()

grammar check_access_list(default)
    match 'ip' fs 'access-list' fs name fs description nl:
        out.enter('$2/$4?description="$6"')
        access_list_items()
    do.return()

**Comment by knipknap** [comment]
Oh, that looks like an issue with the URL parser, I am amazed that we didn't run into this in production yet. I assume it also happens when the output is XML?

I'll have a go at it later this week.

On a side note, we also wrote an IOS and (separate) XR syntax in Gelatin, perhaps we can share them, I'll check soon.

**Comment by knipknap** [comment]
Can you please confirm if it works with the latest version from master?

**Comment by knipknap** [comment]
Also, are you running Python 2 or 3?

**Comment by Gergar** [comment]
Hey sorry just saw it, python 2.

Sent from my iPhone

On Sep 7, 2017, at 5:12 AM, Samuel <notifications@github.com> wrote:

Also, are you running Python 2 or 3?

**Comment by Gergar** [comment]
Let me try i will respond you back if it works :)

Sent from my iPhone

On Sep 7, 2017, at 5:11 AM, Samuel <notifications@github.com> wrote:

Can you please confirm if it works with the latest version from master?

**Comment by Gergar** [comment]
Yes I tested with master branch v 2.0.6-g43b6947 and with the PIP version 2.2 both fails the same :( in python 2

**Comment by knipknap** [comment]
Ouch, could you attach a complete test case? Or send it by mail, if you don't want to put it online. (knipknap@gmail.com)

**Comment by Gergar** [comment]
hey there.. i found the problem now it si working, master branch did not got reloaded at my git copy... i deleted and reload the master now I have version 2.2.5 and the issue is fixed!!!! 

THANK YOU a million!!!

**Comment by knipknap** [comment]
Awesome, Thanks for testing!
