### ISSUE TITLE
Gel Parser for fields within fields(nested)

### ISSUE THREAD

**Issue by sreyafrancis** [knipknap/Gelatin#15]
`Consider` this case wherein there are multiple fields with fields corresponding to each and also the  xml tag which comes by default while using Gelatin has been replaced with Annotation tag:

`<Annotation>      #instead of xml
    <file>img</file>
     <Object>
           <name>cycle</name>
            <boundingbox>      #a field nested in another field
             <x>2.0</x>
             <y>0.3</y>
           </boundingbox>
      </Object>
</Annotation>`

Is it possible to generate a gel file for the specified scenario?

**Comment by knipknap** [comment]
I am not entirely sure I understand what you mean, but if I do, did you have a look at the demos? For example, this demo creates nested output:

https://github.com/knipknap/Gelatin/tree/master/demo/simple

**Comment by sreyafrancis** [comment]
Yes I did go through them. Does the xml file generated with gel parser always begin with the tag named xml?

**Comment by knipknap** [comment]
Oh, that is really a missing feature. I'll see if I can quickly add it...

**Comment by sreyafrancis** [comment]
It is alright. I just wanted to know if that was possible :)
Thank You!

**Comment by knipknap** [comment]
This is now supported in the latest version from master.

**Comment by sreyafrancis** [comment]
Thanks!!
