### ISSUE TITLE
IOS syntax.gel file

### ISSUE THREAD

**Issue by dhop90** [knipknap/Gelatin#17]
According to your post from (https://stackoverflow.com/questions/1191031/cisco-ios-show-conf-to-xml) there are .gel files for IOS.  I can't find the syntax.gel for ios show configuration: syntax/ios/show_running_config/syntax.gel)

**Comment by knipknap** [comment]
Sorry, the syntax is no longer publicly available. I would like to re-publish them at some point, but am not sure if that will ever happen.

You can find some old versions at before af1268ae0bd23316360695777a04125f83a90b9b, but they are *really* outdated.
