### ISSUE TITLE
setup.py does not find module

### ISSUE THREAD

**Issue by CodeSturgeon** [knipknap/Gelatin#2]
### Get a local copy to play with in the usual python way...
- git clone Gelatin
- cd Gelatin
- python setup.py develop
### Unhappy failure

```
    $ gel
    Traceback (most recent call last):
      File "/usr/local/bin/gel", line 7, in <module>
        execfile(__file__)
      File "/Users/fish/Projects/Gelatin/gel", line 19, in <module>
        from Gelatin      import __version__, generator
    ImportError: No module named Gelatin
```
### This is easily fixed with ln

```
    ln -s src/Gelatin Gelatin
```
### ENV

I'm using Python 2.6 on OSX 10.6

**Comment by knipknap** [comment]
This may be solved in 52dcf354d63f3eaa6a4c000367f26622352dbb91; feel free to re-open if the problem persists.
