### ISSUE TITLE
gelatine setup on fedora 

### ISSUE THREAD

**Issue by fredino** [knipknap/Gelatin#23]
hallo everybody ,
I have a couple of questions about Gelatin, since I'm new to deal with it :)

first of all I have a text file, which has a lot of tables inside and I have to use gelatin to convert these tables to json .
the main goal to use json is to monitor my system by using elasticsearch data base so I can show my analysis in Grafana dashboard later .

my question is , how can I download gelatine on my remote server putty so I can use the command of converting the text to json , because when I use it directly , the system send me a message "bash:command is not found ".

thank you all for your help

**Comment by knipknap** [comment]
For future reference: `pip install Gelatin` should do the trick.
