### ISSUE TITLE
getting 'gel' to run from any directory under windows

### ISSUE THREAD

**Issue by maxfieb** [knipknap/Gelatin#3]
I can get the gel script to run from the source dir, or in c:\Python27\Scripts, but i'd expect to be able to run "python gel -s blah.gel inputfile" from any directory, assuming the argument paths are correct and python is in the path.

I would presume that on windows, that gel might need a .py extension and an addition to PATHEXT so the windows shell will run it. Files without extensions in PATHEXT wont run at the shell at all. They need an extension eg: .cmd or .bat  (which run scripts by default) to run at the shell, otherwise you need to call python.exe with gel as the first parameter (but this did not work for me). 

So plain "gel" at the command line wont work, 1. as it is has no extension, and 2. that extension is not in PATHEXT. 

One workaround would be rename gel to add a extension and then add it to PATHEXT so the windows shell will run it :

set PATH=C:\Python27;C:\Python27\Scripts;%PATH%
set PATHEXT=.PY;%PATHEXT%

I renamed gel to gel.py, and now i can run the test script in a non-default location:

C:\Connectivity\python\gelatin\syntax\simple>gel -s syntax.gel input1.txt
<xml>
  <user firstname="John" lastname="Doe">
    <office>1st Ave</office>
    <birth-date>1978-01-01</birth-date>
  </user>
  <user firstname="Jane" lastname="Foo">
    <office>2nd Ave</office>
    <birth-date>1970-01-01</birth-date>
  </user>
</xml>

Admittedly the PATH/PATHEXT should be done by the python install, but having correct file extension on windows is a key.

**Comment by knipknap** [comment]
I am guessing that the issue is not caused by Gelatin, but by the Windows environment, but sorry, I do not have a Windows machine to test with.
